### ISSUE TITLE
error in analyze skeleton output_Table formatting

### ISSUE THREAD

**Issue by pr4deepr** [fiji/AnalyzeSkeleton#17] opened 2020-09-26 07:08 UTC
Hi 
I am having trouble with the data output from Analyse Skeleton and it may have to do with the recent issues with Tables from the recent updates.

It appears that the first column, which is the skeleton id is not appearing and the no of branches ends up being the first column. All the values are shifted by one column, thus reporting the wrong results
I compared this analysis with Analyse skeleton from BoneJ which is included at the bottom of this image.
![image](https://user-images.githubusercontent.com/13831458/94333659-bfaf0480-001a-11eb-8caf-00e245631d8f.png)

Cheers
Pradeep

**Comment by imagejan** [comment] 2020-09-26 14:00
This issue was discussed on the forum as well:

https://forum.image.sc/t/inaccurate-results-from-analyze-skeleton-2d-3d/41306/6?u=imagejan

As far as I can tell, it looks like a regression in ImageJ1, as it doesn't occur with versions of ij.jar prior to 1.52. @rasband did you see this discussion already?

**Comment by rasband** [comment] 2020-09-27 02:35
This regression is fixed in the ImageJ 1.53f20 daily build, or work around it by adding rt.showRowNumbers(true) immediately after creating the ResultTable.

**Closed by rasband** 2020-09-27 02:35 UTC

**Comment by iarganda** [comment] 2020-09-28 08:34
This issue has been fixed following @rasband recommendations in the new release. Thanks all for your help!
